/**
 * Slice 31 — seed exporter: bundled bank (seedActivities.ts + equipmentPieces.ts + seed
 * Säkerhet lines via floorTip) → ONE transaction of idempotent upserts for Supabase.
 * From slice-31/content/export_bank_seed.ts; the row mapping is shared with the app
 * (activityToBankRow in app/src/lib/bankRow.ts) so the bank and the app cannot drift.
 *
 *   bun tools/bank/export-seed.ts            > tools/bank/out/bank-seed.sql
 *   bun tools/bank/export-seed.ts --json     > tools/bank/out/bank-seed.json
 *   bun tools/bank/export-seed.ts --new-only > tools/bank/out/bank-new.sql   (Slice 32+: never overwrite DB edits)
 *
 * Paste the .sql into Supabase → SQL Editor (runs as the project owner; no key involved).
 * Re-running never duplicates rows and never changes `status` (an admin's Dölj stays).
 * The output holds only public exercise texts — no keys, no secrets.
 */
import { seedActivities } from '../../app/src/data/seedActivities.ts'
import { EQUIPMENT_PIECES } from '../../app/src/data/equipmentPieces.ts'
import { floorTip } from '../../app/src/data/activityTips.ts'
import { activityToBankRow } from '../../app/src/lib/bankRow.ts'

const q = (v: string | null | undefined): string =>
  v === null || v === undefined ? 'null' : `'${v.replace(/'/g, "''")}'`
const qb = (v: boolean | undefined, d = false): string => String(v ?? d)
const qj = (v: unknown): string => (v === undefined || v === null ? 'null' : `${q(JSON.stringify(v))}::jsonb`)
const qa = (v: string[] | null | undefined): string =>
  v === undefined || v === null ? 'null' : `array[${v.map(q).join(', ')}]::text[]`

const redskap = EQUIPMENT_PIECES.map((p, i) => ({
  id: p.id,
  label_sv: p.labelSv,
  visual_key: p.visualKey,
  sort_order: (i + 1) * 10,
}))

const exercises = seedActivities.map((a, i) => {
  const { status: _status, ...row } = activityToBankRow(a, i, a.safetyLine?.trim() || floorTip(a).safety || null)
  return row
})

if (process.argv.includes('--json')) {
  console.log(JSON.stringify({ format: 'traningsplaneraren.bank', schemaVersion: 1, redskap, exercises }, null, 2))
  process.exit(0)
}

const out: string[] = []
out.push(`-- Generated by tools/bank/export-seed.ts from seedActivities.ts — ${exercises.length} övningar, ${redskap.length} redskap.`)
out.push('-- Paste into Supabase → SQL Editor → Run (after schema-31.sql). Idempotent; keeps status on re-run.')
out.push('begin;')
out.push('set constraints all deferred;')
for (const r of redskap) {
  out.push(
    `insert into public.redskap (id, label_sv, visual_key, sort_order) values (${q(r.id)}, ${q(r.label_sv)}, ${q(r.visual_key)}, ${r.sort_order})` +
      ` on conflict (id) do update set label_sv = excluded.label_sv, visual_key = excluded.visual_key, sort_order = excluded.sort_order;`,
  )
}
const cols = [
  'id', 'block_type', 'title', 'duration_minutes_default', 'summary', 'how_to', 'watch_for',
  'watch_for_required', 'safety_line', 'visual_key', 'difficulty', 'tags', 'default_station_equipment',
  'legacy_equipment', 'progression_of', 'regression_of', 'experienced_coach_only', 'new_coach_ok',
  'needs_coach_review', 'source', 'sort_order', 'updated_by',
]
const updatable = cols.filter((c) => c !== 'id')
const newOnly = process.argv.includes('--new-only')
for (const e of exercises) {
  const vals = [
    q(e.id), q(e.block_type), q(e.title), String(e.duration_minutes_default), q(e.summary), q(e.how_to),
    q(e.watch_for), qb(e.watch_for_required, true), q(e.safety_line), q(e.visual_key), q(e.difficulty),
    qa(e.tags), qj(e.default_station_equipment), qa(e.legacy_equipment), q(e.progression_of),
    q(e.regression_of), qb(e.experienced_coach_only), qb(e.new_coach_ok), qb(e.needs_coach_review),
    qj(e.source), String(e.sort_order), q('seed-script'),
  ]
  out.push(
    `insert into public.exercises (${cols.join(', ')}) values (${vals.join(', ')})` +
      (newOnly
        ? ' on conflict (id) do nothing;'
        : ` on conflict (id) do update set ${updatable.map((c) => `${c} = excluded.${c}`).join(', ')};`),
  )
}
out.push('commit;')
out.push(`-- Check: select status, count(*) from public.exercises group by status;  → published ${exercises.length}`)
out.push(`-- Check: select count(*) from public.redskap;  → ${redskap.length}`)
console.log(out.join('\n'))
